name: Weekly Contribution Check

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-contributions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm ci

    - name: Run contribution checker
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
      run: node index.js

    - name: Commit push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add week/
        git commit -m "chore: weekly data" || echo "No changes to commit"
        git push